server:
  port: 8080

spring:
  datasource:
    username: root
    password: TEST-skillbox
    url: jdbc:mysql://localhost:3306/test_search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    hikari:
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  profiles:
    active: dev

app:
  search-engine:
    concurrency:
      shutdown-timeout: 25
    jsoup:
      user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36
      referrer: https://www.yandex.ru/
      min-time-out: 4500
      headers:
      - key: Accept-Language
        value: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
      - key: Connection
        value: keep-alive