server:
  port: 8080

spring:
  datasource:
    username: root
    password: TEST-skillbox
    url: jdbc:mysql://localhost:3306/test_search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    hikari:
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  profiles:
    active: dev

app:
  search-engine:
    user-agent: Opera
    referrer: https://yandex.ru/
    min-time-out: 500